steps:
  - name: 'gcr.io/cloud-builders/docker:20.10.24'
    dir: 'web'
    args:
      - build
      - -t
      - gcr.io/naatunadappu/arasiyalaayvu-be
      - -f
      - backend_api/Dockerfile
      - .
images:
  - gcr.io/naatunadappu/arasiyalaayvu-be
